In [22]:
import json

In [34]:
pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: openpyxl in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.23.2 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.1)
Requirement already satisfied: et-xmlfile in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\Anandvj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Step1. Created unstructured format to structured format to csv file

In [108]:
#Hyderabad Cars
import pandas as pd
import ast

# Load the dataset with the correct engine
file_path = 'hyderabad_cars.xlsx'
data = pd.read_excel(file_path, sheet_name='hyderabad_cars.csv', engine='openpyxl')

# Convert string representations of dictionaries into actual dictionaries
data['new_car_detail'] = data['new_car_detail'].apply(ast.literal_eval)
data['new_car_overview'] = data['new_car_overview'].apply(ast.literal_eval)
data['new_car_feature'] = data['new_car_feature'].apply(ast.literal_eval)
data['new_car_specs'] = data['new_car_specs'].apply(ast.literal_eval)

# Function to extract data from nested dictionaries
def extract_details(row):
    details = row.get('new_car_detail', {})
    overview = row.get('new_car_overview', {})
    features = row.get('new_car_feature', {})
    specs = row.get('new_car_specs', {})
    
    # Extracting fields from details
    fuel_type = details.get('ft')
    body_type = details.get('bt')
    kilometers = details.get('km')
    car_price = details.get('price')
    car_model = details.get('model')
    
    
    # Extracting fields from overview (like registration year, model, etc.)
    overview_dict = {item['key']: item['value'] for item in overview.get('top', [])}
    
    # Extracting features (listing them as comma-separated values)
    feature_list = [feature['value'] for feature in features.get('top', [])]
    feature_str = ', '.join(feature_list)
    
    # Extracting specifications (like engine power, mileage, etc.)
    specs_dict = {item['key']: item['value'] for item in specs.get('top', [])}
    
    # Return a flattened structure
    return pd.Series({
        'Fuel Type': fuel_type,
        'Body Type': body_type,
        'Kilometers Driven': kilometers,
        'Registration Year': overview_dict.get('Registration Year'),
        'Car Model': car_model,
        'Ownership': overview_dict.get('Ownership'),
        'Features': feature_str,
        'Engine Power': specs_dict.get('Max Power'),
        'Mileage': specs_dict.get('Mileage'),
        'Car Link': row.get('car_links'),
        'Car Price': car_price
    })

# Apply the extraction function to each row
hyderabad_df = data.apply(extract_details, axis=1)

# Display the structured dataset
print(hyderabad_df.head())

# Save the structured data to a new Excel file (optional)
hyderabad_df.to_csv('hyderabad_cars.csv', index=False)

  Fuel Type  Body Type Kilometers Driven Registration Year        Car Model  \
0    Petrol  Hatchback            20,000              2022  Volkswagen Polo
1    Petrol  Hatchback            85,582          Oct 2014      Hyundai EON
2    Petrol        SUV            10,000              2023    Hyundai Venue
3    Petrol  Hatchback            50,750          Mar 2017    Maruti Baleno
4    Petrol        SUV            10,000              2022    Mahindra Thar

      Ownership                                           Features  \
0   First Owner  Power Steering, Power Windows Front, Air Condi...
1  Second Owner  Power Steering, Power Windows Front, Air Condi...
2   First Owner  Power Steering, Power Windows Front, Air Condi...
3   First Owner  Power Steering, Power Windows Front, Air Condi...
4   First Owner  Power Steering, Power Windows Front, Air Condi...

  Engine Power     Mileage                                           Car Link  \
0    108.62bhp  16.47 kmpl  https://www.cardekho.com/used-car-details/used...
1      55.2bhp   21.1 kmpl  https://www.cardekho.com/buy-used-car-details/...
2     81.80bhp        None  https://www.cardekho.com/used-car-details/used...
3      83.1bhp   21.4 kmpl  https://www.cardekho.com/buy-used-car-details/...
4       150bhp        None  https://www.cardekho.com/used-car-details/used...

      Car Price
0  ₹ 10.44 Lakh
1   ₹ 2.60 Lakh
2   ₹ 9.55 Lakh
3   ₹ 6.71 Lakh
4     ₹ 19 Lakh

In [109]:
hyderabad_df

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Link,Car Price
0,Petrol,Hatchback,"20,000",2022,Volkswagen Polo,First Owner,"Power Steering, Power Windows Front, Air Condi...",108.62bhp,16.47 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 10.44 Lakh
1,Petrol,Hatchback,"85,582",Oct 2014,Hyundai EON,Second Owner,"Power Steering, Power Windows Front, Air Condi...",55.2bhp,21.1 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 2.60 Lakh
2,Petrol,SUV,"10,000",2023,Hyundai Venue,First Owner,"Power Steering, Power Windows Front, Air Condi...",81.80bhp,None,https://www.cardekho.com/used-car-details/used...,₹ 9.55 Lakh
3,Petrol,Hatchback,"50,750",Mar 2017,Maruti Baleno,First Owner,"Power Steering, Power Windows Front, Air Condi...",83.1bhp,21.4 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 6.71 Lakh
4,Petrol,SUV,"10,000",2022,Mahindra Thar,First Owner,"Power Steering, Power Windows Front, Air Condi...",150bhp,None,https://www.cardekho.com/used-car-details/used...,₹ 19 Lakh
...,...,...,...,...,...,...,...,...,...,...,...
1478,Diesel,SUV,"60,000",2013,Mahindra XUV500,First Owner,"Power Steering, Power Windows Front, Air Condi...",140bhp,15.1 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 7 Lakh
1479,Diesel,Sedan,"50,000",2014,Jaguar XF,First Owner,"Power Steering, Power Windows Front, Air Condi...",270.9bhp,14.74 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 20 Lakh
1480,Diesel,Sedan,"1,20,000",2018,BMW 5 Series,Third Owner,"Power Steering, Power Windows Front, Air Condi...",187.74bhp,20.37 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 35 Lakh
1481,Diesel,SUV,"50,000",2019,Tata Nexon,Second Owner,"Power Steering, Power Windows Front, Air Condi...",108.5bhp,21.5 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 8.50 Lakh
1482,Diesel,MUV,"1,00,000",2015,Toyota Innova,First Owner,"Power Steering, Power Windows Front, Air Condi...",100.6bhp,12.99 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 15 Lakh

In [102]:
#Bangalore cars
import pandas as pd
import ast

# Load the dataset with the correct engine
file_path = 'bangalore_cars.xlsx'
data = pd.read_excel(file_path, sheet_name='bangalore_cars.csv', engine='openpyxl')

# Convert string representations of dictionaries into actual dictionaries
data['new_car_detail'] = data['new_car_detail'].apply(ast.literal_eval)
data['new_car_overview'] = data['new_car_overview'].apply(ast.literal_eval)
data['new_car_feature'] = data['new_car_feature'].apply(ast.literal_eval)
data['new_car_specs'] = data['new_car_specs'].apply(ast.literal_eval)

# Function to extract data from nested dictionaries
def extract_details(row):
    details = row.get('new_car_detail', {})
    overview = row.get('new_car_overview', {})
    features = row.get('new_car_feature', {})
    specs = row.get('new_car_specs', {})
    
    # Extracting fields from details
    fuel_type = details.get('ft')
    body_type = details.get('bt')
    kilometers = details.get('km')
    car_price = details.get('price')
    car_model = details.get('model')
    
    
    # Extracting fields from overview (like registration year, model, etc.)
    overview_dict = {item['key']: item['value'] for item in overview.get('top', [])}
    
    # Extracting features (listing them as comma-separated values)
    feature_list = [feature['value'] for feature in features.get('top', [])]
    feature_str = ', '.join(feature_list)
    
    # Extracting specifications (like engine power, mileage, etc.)
    specs_dict = {item['key']: item['value'] for item in specs.get('top', [])}
    
    # Return a flattened structure
    return pd.Series({
        'Fuel Type': fuel_type,
        'Body Type': body_type,
        'Kilometers Driven': kilometers,
        'Registration Year': overview_dict.get('Registration Year'),
        'Car Model': car_model,
        'Ownership': overview_dict.get('Ownership'),
        'Features': feature_str,
        'Engine Power': specs_dict.get('Max Power'),
        'Mileage': specs_dict.get('Mileage'),
        'Car Link': row.get('car_links'),
        'Car Price': car_price
    })

# Apply the extraction function to each row
bangalore_df = data.apply(extract_details, axis=1)

# Display the structured dataset
print(bangalore_df.head())

# Save the structured data to a new Excel file (optional)
bangalore_df.to_csv('bangalore_cars.csv', index=False)

  Fuel Type  Body Type Kilometers Driven Registration Year  \
0    Petrol  Hatchback          1,20,000              2015
1    Petrol        SUV            32,706          Feb 2018
2    Petrol  Hatchback            11,949         Sept 2018
3    Petrol      Sedan            17,794          Dec 2014
4    Diesel        SUV            60,000              2015

            Car Model     Ownership  \
0      Maruti Celerio   Third Owner
1       Ford Ecosport  Second Owner
2          Tata Tiago   First Owner
3       Hyundai Xcent   First Owner
4  Maruti SX4 S Cross   First Owner

                                            Features Engine Power     Mileage  \
0  Power Steering, Power Windows Front, Air Condi...     67.04bhp   23.1 kmpl
1  Power Steering, Power Windows Front, Air Condi...    121.31bhp     17 kmpl
2  Power Steering, Power Windows Front, Air Condi...        84bhp  23.84 kmpl
3  Power Steering, Power Windows Front, Air Condi...     81.86bhp   19.1 kmpl
4  Power Steering, Power Windows Front, Air Condi...      88.5bhp  23.65 kmpl

                                            Car Link    Car Price
0  https://www.cardekho.com/used-car-details/used...     ₹ 4 Lakh
1  https://www.cardekho.com/buy-used-car-details/...  ₹ 8.11 Lakh
2  https://www.cardekho.com/used-car-details/used...  ₹ 5.85 Lakh
3  https://www.cardekho.com/buy-used-car-details/...  ₹ 4.62 Lakh
4  https://www.cardekho.com/used-car-details/used...  ₹ 7.90 Lakh

In [103]:
bangalore_df

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Link,Car Price
0,Petrol,Hatchback,"1,20,000",2015,Maruti Celerio,Third Owner,"Power Steering, Power Windows Front, Air Condi...",67.04bhp,23.1 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 4 Lakh
1,Petrol,SUV,"32,706",Feb 2018,Ford Ecosport,Second Owner,"Power Steering, Power Windows Front, Air Condi...",121.31bhp,17 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 8.11 Lakh
2,Petrol,Hatchback,"11,949",Sept 2018,Tata Tiago,First Owner,"Power Steering, Power Windows Front, Air Condi...",84bhp,23.84 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 5.85 Lakh
3,Petrol,Sedan,"17,794",Dec 2014,Hyundai Xcent,First Owner,"Power Steering, Power Windows Front, Air Condi...",81.86bhp,19.1 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 4.62 Lakh
4,Diesel,SUV,"60,000",2015,Maruti SX4 S Cross,First Owner,"Power Steering, Power Windows Front, Air Condi...",88.5bhp,23.65 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 7.90 Lakh
...,...,...,...,...,...,...,...,...,...,...,...
1476,Diesel,SUV,"1,56,039",May 2012,Toyota Fortuner,Second Owner,"Power Steering, Power Windows Front, Air Condi...",168.5bhp,12.55 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 16.49 Lakh
1477,Petrol,Sedan,"56,000",Jun 2008,Maruti SX4,Second Owner,"Power Steering, Power Windows Front, Air Condi...",104.68,15 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 3.30 Lakh
1478,Petrol,Hatchback,"42,000",Sept 2014,Honda Brio,Second Owner,"Power Steering, Power Windows Front, Air Condi...",86.8bhp,19.4 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 4.25 Lakh
1479,Diesel,Hatchback,"93,003",Dec 2018,Hyundai i20,First Owner,"Power Steering, Power Windows Front, Air Condi...",88.73bhp,22.54 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 7.50 Lakh
1480,Petrol,Hatchback,"36,000",May 2017,Hyundai Grand i10,Second Owner,"Power Steering, Power Windows Front, Air Condi...",82bhp,18.9 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 6.75 Lakh

In [104]:
#chennai_cars
import pandas as pd
import ast

# Load the dataset with the correct engine
file_path = 'chennai_cars.xlsx'
data = pd.read_excel(file_path, sheet_name='chennai_cars.csv', engine='openpyxl')

# Convert string representations of dictionaries into actual dictionaries
data['new_car_detail'] = data['new_car_detail'].apply(ast.literal_eval)
data['new_car_overview'] = data['new_car_overview'].apply(ast.literal_eval)
data['new_car_feature'] = data['new_car_feature'].apply(ast.literal_eval)
data['new_car_specs'] = data['new_car_specs'].apply(ast.literal_eval)

# Function to extract data from nested dictionaries
def extract_details(row):
    details = row.get('new_car_detail', {})
    overview = row.get('new_car_overview', {})
    features = row.get('new_car_feature', {})
    specs = row.get('new_car_specs', {})
    
    # Extracting fields from details
    fuel_type = details.get('ft')
    body_type = details.get('bt')
    kilometers = details.get('km')
    car_price = details.get('price')
    car_model = details.get('model')
    
    
    # Extracting fields from overview (like registration year, model, etc.)
    overview_dict = {item['key']: item['value'] for item in overview.get('top', [])}
    
    # Extracting features (listing them as comma-separated values)
    feature_list = [feature['value'] for feature in features.get('top', [])]
    feature_str = ', '.join(feature_list)
    
    # Extracting specifications (like engine power, mileage, etc.)
    specs_dict = {item['key']: item['value'] for item in specs.get('top', [])}
    
    # Return a flattened structure
    return pd.Series({
        'Fuel Type': fuel_type,
        'Body Type': body_type,
        'Kilometers Driven': kilometers,
        'Registration Year': overview_dict.get('Registration Year'),
        'Car Model': car_model,
        'Ownership': overview_dict.get('Ownership'),
        'Features': feature_str,
        'Engine Power': specs_dict.get('Max Power'),
        'Mileage': specs_dict.get('Mileage'),
        'Car Link': row.get('car_links'),
        'Car Price': car_price
    })

# Apply the extraction function to each row
chennai_df = data.apply(extract_details, axis=1)

# Display the structured dataset
print(chennai_df.head())

# Save the structured data to a new Excel file (optional)
chennai_df.to_csv('chennai_cars.csv', index=False)

  Fuel Type  Body Type Kilometers Driven Registration Year       Car Model  \
0    Petrol        SUV            20,000              2022       Kia Sonet
1    Petrol   Minivans            20,687          Feb 2015     Maruti Eeco
2    Petrol        SUV            30,000              2021  Nissan Magnite
3    Petrol  Hatchback            59,247          May 2015     Hyundai i10
4    Petrol  Hatchback            50,000              2015      Honda Jazz

     Ownership                                           Features  \
0  First Owner  Power Steering, Power Windows Front, Air Condi...
1  First Owner  Low Fuel Warning Light, Accessory Power Outlet...
2  First Owner  Power Steering, Power Windows Front, Air Condi...
3  First Owner  Power Steering, Power Windows Front, Air Condi...
4  First Owner  Power Steering, Power Windows Front, Air Condi...

  Engine Power     Mileage                                           Car Link  \
0    118.36bhp        None  https://www.cardekho.com/used-car-details/used...
1        73bhp  15.37 kmpl  https://www.cardekho.com/buy-used-car-details/...
2     98.63bhp     20 kmpl  https://www.cardekho.com/used-car-details/used...
3     68.05bhp  19.81 kmpl  https://www.cardekho.com/buy-used-car-details/...
4      88.7bhp   18.7 kmpl  https://www.cardekho.com/used-car-details/used...

      Car Price
0  ₹ 11.50 Lakh
1   ₹ 4.15 Lakh
2   ₹ 7.50 Lakh
3   ₹ 3.98 Lakh
4   ₹ 5.50 Lakh

In [105]:
chennai_df

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Link,Car Price
0,Petrol,SUV,"20,000",2022,Kia Sonet,First Owner,"Power Steering, Power Windows Front, Air Condi...",118.36bhp,None,https://www.cardekho.com/used-car-details/used...,₹ 11.50 Lakh
1,Petrol,Minivans,"20,687",Feb 2015,Maruti Eeco,First Owner,"Low Fuel Warning Light, Accessory Power Outlet...",73bhp,15.37 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 4.15 Lakh
2,Petrol,SUV,"30,000",2021,Nissan Magnite,First Owner,"Power Steering, Power Windows Front, Air Condi...",98.63bhp,20 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 7.50 Lakh
3,Petrol,Hatchback,"59,247",May 2015,Hyundai i10,First Owner,"Power Steering, Power Windows Front, Air Condi...",68.05bhp,19.81 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 3.98 Lakh
4,Petrol,Hatchback,"50,000",2015,Honda Jazz,First Owner,"Power Steering, Power Windows Front, Air Condi...",88.7bhp,18.7 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 5.50 Lakh
...,...,...,...,...,...,...,...,...,...,...,...
1414,Petrol,Hatchback,"42,891",Jun 2018,Maruti Swift,First Owner,"Power Steering, Power Windows Front, Air Condi...",81.80bhp,22 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 6.20 Lakh
1415,Diesel,SUV,"59,100",Feb 2019,Renault Duster,First Owner,"Power Steering, Power Windows Front, Air Condi...",83.8bhp,19.87 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 8.90 Lakh
1416,Petrol,SUV,"55,913",Aug 2018,Tata Nexon,First Owner,"Power Steering, Power Windows Front, Air Condi...",108.5bhp,17 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 8.01 Lakh
1417,Diesel,SUV,"65,000",Aug 2017,Volkswagen Tiguan,First Owner,"Power Steering, Power Windows Front, Air Condi...",141bhp,16.65 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 20.50 Lakh
1418,Diesel,Sedan,"60,000",Oct 2019,BMW 3 Series GT,First Owner,"Power Steering, Power Windows Front, Air Condi...",188bhp,21.76 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 35.75 Lakh

In [110]:
#delhi_cars
import pandas as pd
import ast

# Load the dataset with the correct engine
file_path = 'delhi_cars.xlsx'
data = pd.read_excel(file_path, sheet_name='delhi_cars.csv', engine='openpyxl')

# Convert string representations of dictionaries into actual dictionaries
data['new_car_detail'] = data['new_car_detail'].apply(ast.literal_eval)
data['new_car_overview'] = data['new_car_overview'].apply(ast.literal_eval)
data['new_car_feature'] = data['new_car_feature'].apply(ast.literal_eval)
data['new_car_specs'] = data['new_car_specs'].apply(ast.literal_eval)

# Function to extract data from nested dictionaries
def extract_details(row):
    details = row.get('new_car_detail', {})
    overview = row.get('new_car_overview', {})
    features = row.get('new_car_feature', {})
    specs = row.get('new_car_specs', {})
    
    # Extracting fields from details
    fuel_type = details.get('ft')
    body_type = details.get('bt')
    kilometers = details.get('km')
    car_price = details.get('price')
    car_model = details.get('model')
    
    
    # Extracting fields from overview (like registration year, model, etc.)
    overview_dict = {item['key']: item['value'] for item in overview.get('top', [])}
    
    # Extracting features (listing them as comma-separated values)
    feature_list = [feature['value'] for feature in features.get('top', [])]
    feature_str = ', '.join(feature_list)
    
    # Extracting specifications (like engine power, mileage, etc.)
    specs_dict = {item['key']: item['value'] for item in specs.get('top', [])}
    
    # Return a flattened structure
    return pd.Series({
        'Fuel Type': fuel_type,
        'Body Type': body_type,
        'Kilometers Driven': kilometers,
        'Registration Year': overview_dict.get('Registration Year'),
        'Car Model': car_model,
        'Ownership': overview_dict.get('Ownership'),
        'Features': feature_str,
        'Engine Power': specs_dict.get('Max Power'),
        'Mileage': specs_dict.get('Mileage'),
        'Car Link': row.get('car_links'),
        'Car Price': car_price
    })

# Apply the extraction function to each row
delhi_df = data.apply(extract_details, axis=1)

# Display the structured dataset
print(delhi_df.head())

# Save the structured data to a new Excel file (optional)
delhi_df.to_csv('delhi_cars.csv', index=False)

  Fuel Type  Body Type Kilometers Driven Registration Year          Car Model  \
0    Diesel        SUV            10,000              2022         Kia Seltos
1    Petrol        SUV            57,437          May 2016      Hyundai Creta
2    Petrol        SUV             8,000          Dec 2020  Mercedes-Benz GLC
3    Petrol  Hatchback            28,151          Jan 2019       Maruti Swift
4    Petrol        SUV            60,000              2017      Hyundai Creta

      Ownership                                           Features  \
0   First Owner  Power Steering, Power Windows Front, Air Condi...
1  Second Owner  Power Steering, Power Windows Front, Air Condi...
2   First Owner  Power Steering, Power Windows Front, Air Condi...
3  Second Owner  Power Steering, Power Windows Front, Air Condi...
4   First Owner  Power Steering, Power Windows Front, Air Condi...

  Engine Power     Mileage                                           Car Link  \
0    113.43bhp     18 kmpl  https://www.cardekho.com/used-car-details/used...
1     121.3bhp  15.29 kmpl  https://www.cardekho.com/buy-used-car-details/...
2       197bhp  12.74 kmpl  https://www.cardekho.com/used-car-details/used...
3     88.50bhp  22.38 kmpl  https://www.cardekho.com/buy-used-car-details/...
4     121.3bhp  15.29 kmpl  https://www.cardekho.com/used-car-details/used...

     Car Price
0    ₹ 19 Lakh
1  ₹ 7.62 Lakh
2    ₹ 56 Lakh
3  ₹ 5.23 Lakh
4  ₹ 7.65 Lakh

In [111]:
delhi_df

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Link,Car Price
0,Diesel,SUV,"10,000",2022,Kia Seltos,First Owner,"Power Steering, Power Windows Front, Air Condi...",113.43bhp,18 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 19 Lakh
1,Petrol,SUV,"57,437",May 2016,Hyundai Creta,Second Owner,"Power Steering, Power Windows Front, Air Condi...",121.3bhp,15.29 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 7.62 Lakh
2,Petrol,SUV,"8,000",Dec 2020,Mercedes-Benz GLC,First Owner,"Power Steering, Power Windows Front, Air Condi...",197bhp,12.74 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 56 Lakh
3,Petrol,Hatchback,"28,151",Jan 2019,Maruti Swift,Second Owner,"Power Steering, Power Windows Front, Air Condi...",88.50bhp,22.38 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 5.23 Lakh
4,Petrol,SUV,"60,000",2017,Hyundai Creta,First Owner,"Power Steering, Power Windows Front, Air Condi...",121.3bhp,15.29 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 7.65 Lakh
...,...,...,...,...,...,...,...,...,...,...,...
1480,Petrol,Sedan,"60,000",2019,Honda City,First Owner,"Power Steering, Power Windows Front, Air Condi...",117.6bhp,18 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 9 Lakh
1481,Petrol,SUV,"20,000",2021,Kia Sonet,First Owner,"Power Steering, Power Windows Front, Air Condi...",81.86bhp,18.4 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 9.50 Lakh
1482,Petrol,Sedan,"60,000",2011,Hyundai Verna,First Owner,"Power Steering, Power Windows Front, Air Condi...",121.3bhp,17.01 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 4.18 Lakh
1483,Diesel,SUV,"38,000",Oct 2019,Hyundai Creta,First Owner,"Power Steering, Power Windows Front, Air Condi...",126.2bhp,20.5 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 11.95 Lakh
1484,Diesel,SUV,"7,000",None,MG Gloster,None,"Power Steering, Power Windows Front, Air Condi...",212.55bhp,12.04 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 46.40 Lakh

In [85]:
chennai_df.columns

Index(['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year',
       'Model', 'Ownership', 'Features', 'Engine Power', 'Mileage',
       'Car Link'],
      dtype='object')

In [54]:
chennai_df

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Model,Ownership,Features,Engine Power,Mileage,Car Link
0,Petrol,SUV,"20,000",2022,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,None,https://www.cardekho.com/used-car-details/used...
1,Petrol,Minivans,"20,687",Feb 2015,None,First Owner,"Low Fuel Warning Light, Accessory Power Outlet...",None,15.37 kmpl,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,SUV,"30,000",2021,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,20 kmpl,https://www.cardekho.com/used-car-details/used...
3,Petrol,Hatchback,"59,247",May 2015,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,19.81 kmpl,https://www.cardekho.com/buy-used-car-details/...
4,Petrol,Hatchback,"50,000",2015,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,18.7 kmpl,https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...,...,...,...,...,...
1414,Petrol,Hatchback,"42,891",Jun 2018,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,22 kmpl,https://www.cardekho.com/used-car-details/used...
1415,Diesel,SUV,"59,100",Feb 2019,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,19.87 kmpl,https://www.cardekho.com/used-car-details/used...
1416,Petrol,SUV,"55,913",Aug 2018,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,17 kmpl,https://www.cardekho.com/used-car-details/used...
1417,Diesel,SUV,"65,000",Aug 2017,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,16.65 kmpl,https://www.cardekho.com/used-car-details/used...
1418,Diesel,Sedan,"60,000",Oct 2019,None,First Owner,"Power Steering, Power Windows Front, Air Condi...",None,21.76 kmpl,https://www.cardekho.com/used-car-details/used...

In [112]:
#kolkata_cars
import pandas as pd
import ast

# Load the dataset with the correct engine
file_path = 'kolkata_cars.xlsx'
data = pd.read_excel(file_path, sheet_name='kolkata_cars.csv', engine='openpyxl')

# Convert string representations of dictionaries into actual dictionaries
data['new_car_detail'] = data['new_car_detail'].apply(ast.literal_eval)
data['new_car_overview'] = data['new_car_overview'].apply(ast.literal_eval)
data['new_car_feature'] = data['new_car_feature'].apply(ast.literal_eval)
data['new_car_specs'] = data['new_car_specs'].apply(ast.literal_eval)

# Function to extract data from nested dictionaries
def extract_details(row):
    details = row.get('new_car_detail', {})
    overview = row.get('new_car_overview', {})
    features = row.get('new_car_feature', {})
    specs = row.get('new_car_specs', {})
    
    # Extracting fields from details
    fuel_type = details.get('ft')
    body_type = details.get('bt')
    kilometers = details.get('km')
    car_price = details.get('price')
    car_model = details.get('model')
    
    
    # Extracting fields from overview (like registration year, model, etc.)
    overview_dict = {item['key']: item['value'] for item in overview.get('top', [])}
    
    # Extracting features (listing them as comma-separated values)
    feature_list = [feature['value'] for feature in features.get('top', [])]
    feature_str = ', '.join(feature_list)
    
    # Extracting specifications (like engine power, mileage, etc.)
    specs_dict = {item['key']: item['value'] for item in specs.get('top', [])}
    
    # Return a flattened structure
    return pd.Series({
        'Fuel Type': fuel_type,
        'Body Type': body_type,
        'Kilometers Driven': kilometers,
        'Registration Year': overview_dict.get('Registration Year'),
        'Car Model': car_model,
        'Ownership': overview_dict.get('Ownership'),
        'Features': feature_str,
        'Engine Power': specs_dict.get('Max Power'),
        'Mileage': specs_dict.get('Mileage'),
        'Car Link': row.get('car_links'),
        'Car Price': car_price
    })

# Apply the extraction function to each row
kolkata_df = data.apply(extract_details, axis=1)

# Display the structured dataset
print(kolkata_df.head())

# Save the structured data to a new Excel file (optional)
kolkata_df.to_csv('kolkata_cars.csv', index=False)

  Fuel Type  Body Type Kilometers Driven Registration Year      Car Model  \
0    Petrol      Sedan            70,000              2014   Toyota Camry
1    Petrol  Hatchback            23,981          Jul 2017  Datsun RediGO
2    Petrol        SUV             7,100          Nov 2021  Renault Kiger
3    Petrol  Hatchback            71,574          Feb 2012    Hyundai i20
4    Diesel        SUV            50,000              2014        Audi Q3

      Ownership                                           Features  \
0   Third Owner  Power Steering, Power Windows Front, Air Condi...
1   First Owner  Power Steering, Power Windows Front, Air Condi...
2   First Owner  Power Steering, Power Windows Front, Air Condi...
3  Second Owner  Power Steering, Power Windows Front, Air Condi...
4  Second Owner  Power Steering, Power Windows Front, Air Condi...

        Engine Power     Mileage  \
0           158.2bhp  19.16 kmpl
1           53.64bhp   22.7 kmpl
2           71.01bhp  19.03 kmpl
3  80 PS at 5200 rpm     17 kmpl
4          174.33bhp  15.73 kmpl

                                            Car Link    Car Price
0  https://www.cardekho.com/used-car-details/used...  ₹ 9.75 Lakh
1  https://www.cardekho.com/buy-used-car-details/...  ₹ 2.66 Lakh
2  https://www.cardekho.com/used-car-details/used...  ₹ 5.95 Lakh
3  https://www.cardekho.com/buy-used-car-details/...  ₹ 2.23 Lakh
4  https://www.cardekho.com/used-car-details/used...    ₹ 12 Lakh

In [113]:
kolkata_df

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Link,Car Price
0,Petrol,Sedan,"70,000",2014,Toyota Camry,Third Owner,"Power Steering, Power Windows Front, Air Condi...",158.2bhp,19.16 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 9.75 Lakh
1,Petrol,Hatchback,"23,981",Jul 2017,Datsun RediGO,First Owner,"Power Steering, Power Windows Front, Air Condi...",53.64bhp,22.7 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 2.66 Lakh
2,Petrol,SUV,"7,100",Nov 2021,Renault Kiger,First Owner,"Power Steering, Power Windows Front, Air Condi...",71.01bhp,19.03 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 5.95 Lakh
3,Petrol,Hatchback,"71,574",Feb 2012,Hyundai i20,Second Owner,"Power Steering, Power Windows Front, Air Condi...",80 PS at 5200 rpm,17 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 2.23 Lakh
4,Diesel,SUV,"50,000",2014,Audi Q3,Second Owner,"Power Steering, Power Windows Front, Air Condi...",174.33bhp,15.73 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 12 Lakh
...,...,...,...,...,...,...,...,...,...,...,...
1376,Petrol,Hatchback,"10,000",2022,Maruti Celerio,First Owner,"Power Steering, Power Windows Front, Air Condi...",65.71bhp,25.24 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 5.10 Lakh
1377,Petrol,Hatchback,"1,20,000",2014,Maruti Alto 800,First Owner,"Power Steering, Power Windows Front, Air Condi...",47.3bhp,22.74 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 1.80 Lakh
1378,Petrol,Sedan,"50,000",2011,Mercedes-Benz C-Class,Third Owner,"Power Steering, Power Windows Front, Air Condi...",186bhp,11.74 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 5.50 Lakh
1379,Petrol,Hatchback,"40,000",2012,Maruti Ritz,First Owner,"Power Steering, Power Windows Front, Air Condi...",85.80bhp,18.5 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 1.40 Lakh
1380,Diesel,SUV,"1,20,000",2017,Renault Duster,Second Owner,"Power Steering, Power Windows Front, Air Condi...",108.45bhp,19.72 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 5 Lakh

Add a city column in a data

In [114]:
#Add a city column
import pandas as pd

# Load the dataset
kolkata_df = pd.read_csv('kolkata_cars.csv')
bangalore_df = pd.read_csv('bangalore_cars.csv')
chennai_df = pd.read_csv('chennai_cars.csv')
delhi_df = pd.read_csv('delhi_cars.csv')
hyderabad_df = pd.read_csv('hyderabad_cars.csv')

# Add a new column 'City' and assign the value to all rows
kolkata_df['City'] = 'Kolkata'
bangalore_df['City'] = 'Bangalore'
chennai_df['City'] = 'Chennai'
delhi_df['City'] = 'Delhi'
hyderabad_df['City'] = 'Hyderabad'

# Concatenate all datasets into a single dataset
combined_df = pd.concat([kolkata_df,bangalore_df,chennai_df,delhi_df,hyderabad_df])

# Save the combined dataset to a new CSV file
combined_df.to_csv('combined_cars.csv', index=False)

In [86]:
combined_df.columns

Index(['Fuel Type', 'Body Type', 'Kilometers Driven', 'Registration Year',
       'Model', 'Ownership', 'Features', 'Engine Power', 'Mileage', 'Car Link',
       'City'],
      dtype='object')

In [115]:
combined_df

,Fuel Type,Body Type,Kilometers Driven,Registration Year,Car Model,Ownership,Features,Engine Power,Mileage,Car Link,Car Price,City
0,Petrol,Sedan,"70,000",2014,Toyota Camry,Third Owner,"Power Steering, Power Windows Front, Air Condi...",158.2bhp,19.16 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 9.75 Lakh,Kolkata
1,Petrol,Hatchback,"23,981",Jul 2017,Datsun RediGO,First Owner,"Power Steering, Power Windows Front, Air Condi...",53.64bhp,22.7 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 2.66 Lakh,Kolkata
2,Petrol,SUV,"7,100",Nov 2021,Renault Kiger,First Owner,"Power Steering, Power Windows Front, Air Condi...",71.01bhp,19.03 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 5.95 Lakh,Kolkata
3,Petrol,Hatchback,"71,574",Feb 2012,Hyundai i20,Second Owner,"Power Steering, Power Windows Front, Air Condi...",80 PS at 5200 rpm,17 kmpl,https://www.cardekho.com/buy-used-car-details/...,₹ 2.23 Lakh,Kolkata
4,Diesel,SUV,"50,000",2014,Audi Q3,Second Owner,"Power Steering, Power Windows Front, Air Condi...",174.33bhp,15.73 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 12 Lakh,Kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...
1478,Diesel,SUV,"60,000",2013,Mahindra XUV500,First Owner,"Power Steering, Power Windows Front, Air Condi...",140bhp,15.1 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 7 Lakh,Hyderabad
1479,Diesel,Sedan,"50,000",2014,Jaguar XF,First Owner,"Power Steering, Power Windows Front, Air Condi...",270.9bhp,14.74 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 20 Lakh,Hyderabad
1480,Diesel,Sedan,"1,20,000",2018,BMW 5 Series,Third Owner,"Power Steering, Power Windows Front, Air Condi...",187.74bhp,20.37 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 35 Lakh,Hyderabad
1481,Diesel,SUV,"50,000",2019,Tata Nexon,Second Owner,"Power Steering, Power Windows Front, Air Condi...",108.5bhp,21.5 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 8.50 Lakh,Hyderabad
1482,Diesel,MUV,"1,00,000",2015,Toyota Innova,First Owner,"Power Steering, Power Windows Front, Air Condi...",100.6bhp,12.99 kmpl,https://www.cardekho.com/used-car-details/used...,₹ 15 Lakh,Hyderabad

Handling Missing values

In [116]:
import pandas as pd

# Load the dataset
#kolkata_df = pd.read_csv('kolkata_cars.csv')
kolkata_df = pd.read_csv('kolkata_cars.csv')
bangalore_df = pd.read_csv('bangalore_cars.csv')
chennai_df = pd.read_csv('chennai_cars.csv')
delhi_df = pd.read_csv('delhi_cars.csv')
hyderabad_df = pd.read_csv('hyderabad_cars.csv')



# Handle missing values for numerical columns
# Impute with mean for numerical columns
numerical_columns = kolkata_df.select_dtypes(include=['float64', 'int64']).columns
kolkata_df[numerical_columns] = kolkata_df[numerical_columns].apply(lambda x: x.fillna(x.mean()))

numerical_columns = bangalore_df.select_dtypes(include=['float64', 'int64']).columns
bangalore_df[numerical_columns] = bangalore_df[numerical_columns].apply(lambda x: x.fillna(x.mean()))

numerical_columns = chennai_df.select_dtypes(include=['float64', 'int64']).columns
chennai_df[numerical_columns] = chennai_df[numerical_columns].apply(lambda x: x.fillna(x.mean()))

numerical_columns = delhi_df.select_dtypes(include=['float64', 'int64']).columns
delhi_df[numerical_columns] = delhi_df[numerical_columns].apply(lambda x: x.fillna(x.mean()))

numerical_columns = hyderabad_df.select_dtypes(include=['float64', 'int64']).columns
hyderabad_df[numerical_columns] = hyderabad_df[numerical_columns].apply(lambda x: x.fillna(x.mean()))


# Alternatively, you can use median or mode for imputation
# kolkata_df[numerical_columns] = kolkata_df[numerical_columns].apply(lambda x: x.fillna(x.median()))
# kolkata_df[numerical_columns] = kolkata_df[numerical_columns].apply(lambda x: x.fillna(x.mode()[0]))

# Handle missing values for categorical columns
# Impute with mode for categorical columns
categorical_columns = kolkata_df.select_dtypes(include=['object']).columns
kolkata_df[categorical_columns] = kolkata_df[categorical_columns].apply(lambda x: x.fillna(x.mode()[0]))

categorical_columns = bangalore_df.select_dtypes(include=['object']).columns
bangalore_df[categorical_columns] = bangalore_df[categorical_columns].apply(lambda x: x.fillna(x.mode()[0]))

categorical_columns = chennai_df.select_dtypes(include=['object']).columns
chennai_df[categorical_columns] = chennai_df[categorical_columns].apply(lambda x: x.fillna(x.mode()[0]))

categorical_columns = delhi_df.select_dtypes(include=['object']).columns
delhi_df[categorical_columns] = delhi_df[categorical_columns].apply(lambda x: x.fillna(x.mode()[0]))

categorical_columns = hyderabad_df.select_dtypes(include=['object']).columns
hyderabad_df[categorical_columns] = hyderabad_df[categorical_columns].apply(lambda x: x.fillna(x.mode()[0]))

# Alternatively, you can create a new category for missing values
# kolkata_df[categorical_columns] = kolkata_df[categorical_columns].apply(lambda x: x.fillna('Missing'))

# Save the cleaned dataset
kolkata_df.to_csv('kolkata_cars_cleaned.csv', index=False)
bangalore_df.to_csv('bangalore_cars_cleaned.csv', index=False)
chennai_df.to_csv('chennai_cars_cleaned.csv', index=False)
delhi_df.to_csv('delhi_cars_cleaned.csv', index=False)
hyderabad_df.to_csv('hyderabad_cars_cleaned.csv', index=False)

Standardised Data formats

In [117]:
import pandas as pd
import re

# Load the dataset
kolkata_df = pd.read_csv('kolkata_cars.csv')
bangalore_df = pd.read_csv('bangalore_cars.csv')
chennai_df = pd.read_csv('chennai_cars.csv')
delhi_df = pd.read_csv('delhi_cars.csv')
hyderabad_df = pd.read_csv('hyderabad_cars.csv')


# Function to clean and convert string formats to integers
def clean_numeric_column(column):
    # Remove non-numeric characters using regex
    column = column.apply(lambda x: re.sub(r'\D', '', str(x)) if pd.notnull(x) else x)
    # Convert the cleaned column to numeric type (integer or float)
    column = pd.to_numeric(column, errors='coerce')
    return column

# Example: Clean and convert the 'mileage' column if it contains values like '70 kms'
if 'mileage' in kolkata_df.columns:
    kolkata_df['mileage'] = clean_numeric_column(kolkata_df['mileage'])

# Repeat the process for other relevant columns
# Example: Clean and convert the 'engine_size' column if it contains values like '1200 cc'
if 'engine_size' in kolkata_df.columns:
    kolkata_df['engine_size'] = clean_numeric_column(kolkata_df['engine_size'])

# Check and convert other columns to appropriate data types
# Example: Convert 'year' column to integer if it's not already
if 'year' in kolkata_df.columns:
    kolkata_df['year'] = pd.to_numeric(kolkata_df['year'], errors='coerce')

# Function to clean and convert string formats to integers
def clean_numeric_column(column):
    # Remove non-numeric characters using regex
    column = column.apply(lambda x: re.sub(r'\D', '', str(x)) if pd.notnull(x) else x)
    # Convert the cleaned column to numeric type (integer or float)
    column = pd.to_numeric(column, errors='coerce')
    return column

# Example: Clean and convert the 'mileage' column if it contains values like '70 kms'
if 'mileage' in bangalore_df.columns:
    bangalore_df['mileage'] = clean_numeric_column(bangalore_df['mileage'])

# Repeat the process for other relevant columns
# Example: Clean and convert the 'engine_size' column if it contains values like '1200 cc'
if 'engine_size' in bangalore_df.columns:
    bangalore_df['engine_size'] = clean_numeric_column(bangalore_df['engine_size'])

# Check and convert other columns to appropriate data types
# Example: Convert 'year' column to integer if it's not already
if 'year' in bangalore_df.columns:
    bangalore_df['year'] = pd.to_numeric(bangalore_df['year'], errors='coerce')

# Function to clean and convert string formats to integers
def clean_numeric_column(column):
    # Remove non-numeric characters using regex
    column = column.apply(lambda x: re.sub(r'\D', '', str(x)) if pd.notnull(x) else x)
    # Convert the cleaned column to numeric type (integer or float)
    column = pd.to_numeric(column, errors='coerce')
    return column

# Example: Clean and convert the 'mileage' column if it contains values like '70 kms'
if 'mileage' in chennai_df.columns:
    chennai_df['mileage'] = clean_numeric_column(chennai_df['mileage'])

# Repeat the process for other relevant columns
# Example: Clean and convert the 'engine_size' column if it contains values like '1200 cc'
if 'engine_size' in chennai_df.columns:
    chennai_df['engine_size'] = clean_numeric_column(chennai_df['engine_size'])

# Check and convert other columns to appropriate data types
# Example: Convert 'year' column to integer if it's not already
if 'year' in chennai_df.columns:
    chennai_df['year'] = pd.to_numeric(chennai_df['year'], errors='coerce')


# Function to clean and convert string formats to integers
def clean_numeric_column(column):
    # Remove non-numeric characters using regex
    column = column.apply(lambda x: re.sub(r'\D', '', str(x)) if pd.notnull(x) else x)
    # Convert the cleaned column to numeric type (integer or float)
    column = pd.to_numeric(column, errors='coerce')
    return column

# Example: Clean and convert the 'mileage' column if it contains values like '70 kms'
if 'mileage' in delhi_df.columns:
    delhi_df['mileage'] = clean_numeric_column(delhi_df['mileage'])

# Repeat the process for other relevant columns
# Example: Clean and convert the 'engine_size' column if it contains values like '1200 cc'
if 'engine_size' in delhi_df.columns:
    delhi_df['engine_size'] = clean_numeric_column(delhi_df['engine_size'])

# Check and convert other columns to appropriate data types
# Example: Convert 'year' column to integer if it's not already
if 'year' in delhi_df.columns:
    delhi_df['year'] = pd.to_numeric(delhi_df['year'], errors='coerce')

# Function to clean and convert string formats to integers
def clean_numeric_column(column):
    # Remove non-numeric characters using regex
    column = column.apply(lambda x: re.sub(r'\D', '', str(x)) if pd.notnull(x) else x)
    # Convert the cleaned column to numeric type (integer or float)
    column = pd.to_numeric(column, errors='coerce')
    return column

# Example: Clean and convert the 'mileage' column if it contains values like '70 kms'
if 'mileage' in hyderabad_df.columns:
    hyderabad_df['mileage'] = clean_numeric_column(hyderabad_df['mileage'])

# Repeat the process for other relevant columns
# Example: Clean and convert the 'engine_size' column if it contains values like '1200 cc'
if 'engine_size' in hyderabad_df.columns:
    hyderabad_df['engine_size'] = clean_numeric_column(hyderabad_df['engine_size'])

# Check and convert other columns to appropriate data types
# Example: Convert 'year' column to integer if it's not already
if 'year' in hyderabad_df.columns:
    hyderabad_df['year'] = pd.to_numeric(hyderabad_df['year'], errors='coerce')

# Ensure categorical columns are of type 'category'
categorical_columns = kolkata_df.select_dtypes(include=['object']).columns
kolkata_df[categorical_columns] = kolkata_df[categorical_columns].astype('category')

categorical_columns = bangalore_df.select_dtypes(include=['object']).columns
bangalore_df[categorical_columns] = bangalore_df[categorical_columns].astype('category')

categorical_columns = chennai_df.select_dtypes(include=['object']).columns
chennai_df[categorical_columns] = chennai_df[categorical_columns].astype('category')

categorical_columns = delhi_df.select_dtypes(include=['object']).columns
delhi_df[categorical_columns] = delhi_df[categorical_columns].astype('category')

categorical_columns = hyderabad_df.select_dtypes(include=['object']).columns
hyderabad_df[categorical_columns] = hyderabad_df[categorical_columns].astype('category')

# Save the cleaned and standardized dataset
kolkata_df.to_csv('kolkata_cars_standardized.csv', index=False)
bangalore_df.to_csv('bangalore_cars_standardized.csv', index=False)
chennai_df.to_csv('chennai_cars_standardized.csv', index=False)
delhi_df.to_csv('delhi_cars_standardized.csv', index=False)
hyderabad_df.to_csv('hyderabad_cars_standardized.csv', index=False)

In [119]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler, StandardScaler
import numpy as np

# Function to encode categorical variables
def encode_categorical(df):
    # One-Hot Encoding for nominal categorical variables
    nominal_columns = ['City', 'Fuel_Type', 'Transmission']  # Example nominal columns
    df = pd.get_dummies(df, columns=nominal_columns, drop_first=True)
    
    # Label Encoding for ordinal categorical variables
    # Example ordinal column: 'Condition' (new, like_new, used, ...)
    if 'Condition' in df.columns:
        condition_order = ['Poor', 'Fair', 'Good', 'Very Good', 'Excellent']  # Adjust based on your data
        condition_encoder = LabelEncoder()
        df['Condition'] = condition_encoder.fit_transform(df['Condition'])
    
    return df

# Function to normalize numerical features
def normalize_numerical(df, scaling_type='minmax'):
    numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
    
    if scaling_type == 'minmax':
        scaler = MinMaxScaler()
    else:
        scaler = StandardScaler()
    
    df[numerical_columns] = scaler.fit_transform(df[numerical_columns])
    
    return df

# Function to remove or cap outliers using IQR method
def remove_outliers(df):
    numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
    
    for col in numerical_columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # Remove outliers
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
        
        # Alternatively, you can cap the outliers instead of removing them
        # df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
        # df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])
    
    return df

# Load the dataset (Replace this with the actual file path)
kolkata_df = pd.read_csv('kolkata_cars.csv')
bangalore_df = pd.read_csv('bangalore_cars.csv')
chennai_df = pd.read_csv('chennai_cars.csv')
delhi_df = pd.read_csv('delhi_cars.csv')
hyderabad_df = pd.read_csv('hyderabad_cars.csv')


# Normalize numerical features (use 'minmax' or 'standard' for scaling_type)
kolkata_df = normalize_numerical(kolkata_df, scaling_type='minmax')
bangalore_df = normalize_numerical(bangalore_df, scaling_type='minmax')
chennai_df = normalize_numerical(chennai_df, scaling_type='minmax')
delhi_df = normalize_numerical(delhi_df, scaling_type='minmax')
hyderabad_df = normalize_numerical(hyderabad_df, scaling_type='minmax')


# Remove outliers using IQR method
kolkata_df = remove_outliers(kolkata_df)
bangalore_df = remove_outliers(bangalore_df)
chennai_df = remove_outliers(chennai_df)
delhi_df = remove_outliers(delhi_df)
hyderabad_df = remove_outliers(hyderabad_df)

# Save the processed dataset
kolkata_df.to_csv('kolkata_cars_processed.csv', index=False)
bangalore_df.to_csv('bangalore_processed.csv', index=False)
chennai_df.to_csv('chennai_cars_processed.csv', index=False)
delhi_df.to_csv('kolkata_cars_processed.csv', index=False)
hyderabad_df.to_csv('hyderabad_cars_processed.csv', index=False)

ValueError: at least one array or dtype is required

In [76]:
pip install matplotlib seaborn scikit-learn

Collecting matplotlib
  Downloading matplotlib-3.9.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: scikit-learn in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.5.1)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.2.1-cp311-cp311-win_amd64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.53.1-cp311-cp311-win_amd64.whl.metadata (165 kB)
     ---------------------------------------- 0.0/165.9 kB ? eta -:--:--
     ------------------------------------  163.8/165.9 kB 10.2 MB/s eta 0:00:01
     -------------------------------------- 165.9/165.9 kB 5.0 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.5-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (10.4.0)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Downloading matplotlib-3.9.2-cp311-cp311-win_amd64.whl (7.8 MB)
   ---------------------------------------- 0.0/7.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.8 MB 10.7 MB/s eta 0:00:01
   ----- ---------------------------------- 1.1/7.8 MB 11.5 MB/s eta 0:00:01
   -------- ------------------------------- 1.6/7.8 MB 11.1 MB/s eta 0:00:01
   ---------- ----------------------------- 2.0/7.8 MB 10.8 MB/s eta 0:00:01
   ------------- -------------------------- 2.6/7.8 MB 11.7 MB/s eta 0:00:01
   --------------- ------------------------ 3.0/7.8 MB 11.4 MB/s eta 0:00:01
   ------------------ --------------------- 3.6/7.8 MB 11.6 MB/s eta 0:00:01
   --------------------- ------------------ 4.2/7.8 MB 11.6 MB/s eta 0:00:01
   ------------------------ --------------- 4.7/7.8 MB 11.6 MB/s eta 0:00:01
   -------------------------- ------------- 5.2/7.8 MB 11.4 MB/s eta 0:00:01
   ----------------------------- ---------- 5.7/7.8 MB 11.8 MB/s eta 0:00:01
   ------------------------------- -------- 6.2/7.8 MB 11.3 MB/s eta 0:00:01
   --------------------------------- ------ 6.6/7.8 MB 11.5 MB/s eta 0:00:01
   ------------------------------------ --- 7.2/7.8 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  7.8/7.8 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 7.8/7.8 MB 11.1 MB/s eta 0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 294.9/294.9 kB 8.9 MB/s eta 0:00:00
Downloading contourpy-1.2.1-cp311-cp311-win_amd64.whl (188 kB)
   ---------------------------------------- 0.0/188.2 kB ? eta -:--:--
   --------------------------------------  184.3/188.2 kB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 188.2/188.2 kB 3.8 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.53.1-cp311-cp311-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------- ----------------------------- 0.6/2.2 MB 9.3 MB/s eta 0:00:01
   -------------------- ------------------- 1.1/2.2 MB 11.7 MB/s eta 0:00:01
   ------------------------------ --------- 1.7/2.2 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------  2.2/2.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 10.0 MB/s eta 0:00:00
Downloading kiwisolver-1.4.5-cp311-cp311-win_amd64.whl (56 kB)
   ---------------------------------------- 0.0/56.1 kB ? eta -:--:--
   ---------------------------------------- 56.1/56.1 kB 2.9 MB/s eta 0:00:00
Downloading pyparsing-3.1.2-py3-none-any.whl (103 kB)
   ---------------------------------------- 0.0/103.2 kB ? eta -:--:--
   ---------------------------------------- 103.2/103.2 kB ? eta 0:00:00
Installing collected packages: pyparsing, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
Successfully installed contourpy-1.2.1 cycler-0.12.1 fonttools-4.53.1 kiwisolver-1.4.5 matplotlib-3.9.2 pyparsing-3.1.2 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\Anandvj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [77]:
!pip install matplotlib seaborn scikit-learn

Requirement already satisfied: matplotlib in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.9.2)
Requirement already satisfied: seaborn in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.5.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.23 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\anandvj\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\Anandvj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

2.Exploratory Data Analysis (EDA)

In [120]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Load each dataset
kolkata_cars = pd.read_csv('kolkata_cars.csv')
chennai_cars = pd.read_csv('chennai_cars.csv')
delhi_cars = pd.read_csv('delhi_cars.csv')
hyderabad_cars = pd.read_csv('hyderabad_cars.csv')
bangalore_cars = pd.read_csv('bangalore_cars.csv')

# Function to calculate and display descriptive statistics
def display_statistics(df, city_name):
    print(f"\nDescriptive Statistics for {city_name}:")
    print("First few rows of the dataset:")
    print(df.head())

    # Filter numeric columns
    numeric_df = df.select_dtypes(include='number')

    if not numeric_df.empty:
        mean = numeric_df.mean()
        median = numeric_df.median()
        
        # Handle mode calculation
        mode_df = numeric_df.mode()
        mode = mode_df.iloc[0] if not mode_df.empty else 'No mode'
        
        std_dev = numeric_df.std()

        print("\nMean of each column:")
        print(mean)

        print("\nMedian of each column:")
        print(median)

        print("\nMode of each column:")
        print(mode)

        print("\nStandard Deviation of each column:")
        print(std_dev)

        print("\nDescriptive Statistics (using describe method):")
        print(numeric_df.describe())
    else:
        print("No numeric columns available for statistics.")

    return numeric_df.describe() if not numeric_df.empty else None

# Function to visualize data
def visualize_data(df, city_name):
    print(f"\nData Visualization for {city_name}:")

    # Filter numeric columns
    numeric_df = df.select_dtypes(include='number')

    if not numeric_df.empty:
        # Histograms for all numeric columns
        numeric_df.hist(bins=20, figsize=(10, 10))
        plt.suptitle(f'Histograms for {city_name}')
        plt.show()

        # Scatter plot matrix
        sns.pairplot(numeric_df)
        plt.suptitle(f'Scatter Plot Matrix for {city_name}')
        plt.show()

        # Box plots for all numeric columns
        numeric_df.plot(kind='box', subplots=True, layout=(3, 3), figsize=(15, 10))
        plt.suptitle(f'Box Plots for {city_name}')
        plt.show()

        # Correlation heatmap
        corr_matrix = numeric_df.corr()
        plt.figure(figsize=(12, 8))
        sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
        plt.title(f'Correlation Heatmap for {city_name}')
        plt.show()
    else:
        print("No numeric columns available for visualization.")

# Function for feature selection using correlation and feature importance
def feature_selection(df, city_name, target_column):
    print(f"\nFeature Selection for {city_name}:")

    # Filter numeric columns
    numeric_df = df.select_dtypes(include='number')

    if target_column in numeric_df.columns:
        # Correlation analysis
        corr_matrix = numeric_df.corr()
        print("\nCorrelation with target column:")
        print(corr_matrix[target_column].sort_values(ascending=False))

        # Feature importance using RandomForest
        X = numeric_df.drop(columns=[target_column])
        y = numeric_df[target_column]

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        model = RandomForestRegressor(random_state=42)
        model.fit(X_train, y_train)

        feature_importances = pd.Series(model.feature_importances_, index=X.columns)
        feature_importances = feature_importances.sort_values(ascending=False)

        print("\nFeature Importance from RandomForestRegressor:")
        print(feature_importances)

        # Visualize feature importance
        feature_importances.plot(kind='bar', figsize=(10, 6))
        plt.title(f'Feature Importance for {city_name}')
        plt.show()
    else:
        print(f"Target column '{target_column}' is not in the dataset.")

# Apply functions to each city's dataset
for city_df, city_name in zip(
        [kolkata_cars, chennai_cars, delhi_cars, hyderabad_cars, bangalore_cars],
        ['Kolkata', 'Chennai', 'Delhi', 'Hyderabad', 'Bangalore']):
    
    # Assuming 'Price' is the target column for prediction
    target_column = 'Price'

    display_statistics(city_df, city_name)
    visualize_data(city_df, city_name)
    feature_selection(city_df, city_name, target_column)

Descriptive Statistics for Kolkata:
First few rows of the dataset:
  Fuel Type  Body Type Kilometers Driven Registration Year      Car Model  \
0    Petrol      Sedan            70,000              2014   Toyota Camry
1    Petrol  Hatchback            23,981          Jul 2017  Datsun RediGO
2    Petrol        SUV             7,100          Nov 2021  Renault Kiger
3    Petrol  Hatchback            71,574          Feb 2012    Hyundai i20
4    Diesel        SUV            50,000              2014        Audi Q3

      Ownership                                           Features  \
0   Third Owner  Power Steering, Power Windows Front, Air Condi...
1   First Owner  Power Steering, Power Windows Front, Air Condi...
2   First Owner  Power Steering, Power Windows Front, Air Condi...
3  Second Owner  Power Steering, Power Windows Front, Air Condi...
4  Second Owner  Power Steering, Power Windows Front, Air Condi...

        Engine Power     Mileage  \
0           158.2bhp  19.16 kmpl
1           53.64bhp   22.7 kmpl
2           71.01bhp  19.03 kmpl
3  80 PS at 5200 rpm     17 kmpl
4          174.33bhp  15.73 kmpl

                                            Car Link    Car Price
0  https://www.cardekho.com/used-car-details/used...  ₹ 9.75 Lakh
1  https://www.cardekho.com/buy-used-car-details/...  ₹ 2.66 Lakh
2  https://www.cardekho.com/used-car-details/used...  ₹ 5.95 Lakh
3  https://www.cardekho.com/buy-used-car-details/...  ₹ 2.23 Lakh
4  https://www.cardekho.com/used-car-details/used...    ₹ 12 Lakh
No numeric columns available for statistics.

Data Visualization for Kolkata:
No numeric columns available for visualization.

Feature Selection for Kolkata:
Target column 'Price' is not in the dataset.

Descriptive Statistics for Chennai:
First few rows of the dataset:
  Fuel Type  Body Type Kilometers Driven Registration Year       Car Model  \
0    Petrol        SUV            20,000              2022       Kia Sonet
1    Petrol   Minivans            20,687          Feb 2015     Maruti Eeco
2    Petrol        SUV            30,000              2021  Nissan Magnite
3    Petrol  Hatchback            59,247          May 2015     Hyundai i10
4    Petrol  Hatchback            50,000              2015      Honda Jazz

     Ownership                                           Features  \
0  First Owner  Power Steering, Power Windows Front, Air Condi...
1  First Owner  Low Fuel Warning Light, Accessory Power Outlet...
2  First Owner  Power Steering, Power Windows Front, Air Condi...
3  First Owner  Power Steering, Power Windows Front, Air Condi...
4  First Owner  Power Steering, Power Windows Front, Air Condi...

  Engine Power     Mileage                                           Car Link  \
0    118.36bhp         NaN  https://www.cardekho.com/used-car-details/used...
1        73bhp  15.37 kmpl  https://www.cardekho.com/buy-used-car-details/...
2     98.63bhp     20 kmpl  https://www.cardekho.com/used-car-details/used...
3     68.05bhp  19.81 kmpl  https://www.cardekho.com/buy-used-car-details/...
4      88.7bhp   18.7 kmpl  https://www.cardekho.com/used-car-details/used...

      Car Price
0  ₹ 11.50 Lakh
1   ₹ 4.15 Lakh
2   ₹ 7.50 Lakh
3   ₹ 3.98 Lakh
4   ₹ 5.50 Lakh
No numeric columns available for statistics.

Data Visualization for Chennai:
No numeric columns available for visualization.

Feature Selection for Chennai:
Target column 'Price' is not in the dataset.

Descriptive Statistics for Delhi:
First few rows of the dataset:
  Fuel Type  Body Type Kilometers Driven Registration Year          Car Model  \
0    Diesel        SUV            10,000              2022         Kia Seltos
1    Petrol        SUV            57,437          May 2016      Hyundai Creta
2    Petrol        SUV             8,000          Dec 2020  Mercedes-Benz GLC
3    Petrol  Hatchback            28,151          Jan 2019       Maruti Swift
4    Petrol        SUV            60,000              2017      Hyundai Creta

      Ownership                                           Features  \
0   First Owner  Power Steering, Power Windows Front, Air Condi...
1  Second Owner  Power Steering, Power Windows Front, Air Condi...
2   First Owner  Power Steering, Power Windows Front, Air Condi...
3  Second Owner  Power Steering, Power Windows Front, Air Condi...
4   First Owner  Power Steering, Power Windows Front, Air Condi...

  Engine Power     Mileage                                           Car Link  \
0    113.43bhp     18 kmpl  https://www.cardekho.com/used-car-details/used...
1     121.3bhp  15.29 kmpl  https://www.cardekho.com/buy-used-car-details/...
2       197bhp  12.74 kmpl  https://www.cardekho.com/used-car-details/used...
3     88.50bhp  22.38 kmpl  https://www.cardekho.com/buy-used-car-details/...
4     121.3bhp  15.29 kmpl  https://www.cardekho.com/used-car-details/used...

     Car Price
0    ₹ 19 Lakh
1  ₹ 7.62 Lakh
2    ₹ 56 Lakh
3  ₹ 5.23 Lakh
4  ₹ 7.65 Lakh
No numeric columns available for statistics.

Data Visualization for Delhi:
No numeric columns available for visualization.

Feature Selection for Delhi:
Target column 'Price' is not in the dataset.

Descriptive Statistics for Hyderabad:
First few rows of the dataset:
  Fuel Type  Body Type Kilometers Driven Registration Year        Car Model  \
0    Petrol  Hatchback            20,000              2022  Volkswagen Polo
1    Petrol  Hatchback            85,582          Oct 2014      Hyundai EON
2    Petrol        SUV            10,000              2023    Hyundai Venue
3    Petrol  Hatchback            50,750          Mar 2017    Maruti Baleno
4    Petrol        SUV            10,000              2022    Mahindra Thar

      Ownership                                           Features  \
0   First Owner  Power Steering, Power Windows Front, Air Condi...
1  Second Owner  Power Steering, Power Windows Front, Air Condi...
2   First Owner  Power Steering, Power Windows Front, Air Condi...
3   First Owner  Power Steering, Power Windows Front, Air Condi...
4   First Owner  Power Steering, Power Windows Front, Air Condi...

  Engine Power     Mileage                                           Car Link  \
0    108.62bhp  16.47 kmpl  https://www.cardekho.com/used-car-details/used...
1      55.2bhp   21.1 kmpl  https://www.cardekho.com/buy-used-car-details/...
2     81.80bhp         NaN  https://www.cardekho.com/used-car-details/used...
3      83.1bhp   21.4 kmpl  https://www.cardekho.com/buy-used-car-details/...
4       150bhp         NaN  https://www.cardekho.com/used-car-details/used...

      Car Price
0  ₹ 10.44 Lakh
1   ₹ 2.60 Lakh
2   ₹ 9.55 Lakh
3   ₹ 6.71 Lakh
4     ₹ 19 Lakh
No numeric columns available for statistics.

Data Visualization for Hyderabad:
No numeric columns available for visualization.

Feature Selection for Hyderabad:
Target column 'Price' is not in the dataset.

Descriptive Statistics for Bangalore:
First few rows of the dataset:
  Fuel Type  Body Type Kilometers Driven Registration Year  \
0    Petrol  Hatchback          1,20,000              2015
1    Petrol        SUV            32,706          Feb 2018
2    Petrol  Hatchback            11,949         Sept 2018
3    Petrol      Sedan            17,794          Dec 2014
4    Diesel        SUV            60,000              2015

            Car Model     Ownership  \
0      Maruti Celerio   Third Owner
1       Ford Ecosport  Second Owner
2          Tata Tiago   First Owner
3       Hyundai Xcent   First Owner
4  Maruti SX4 S Cross   First Owner

                                            Features Engine Power     Mileage  \
0  Power Steering, Power Windows Front, Air Condi...     67.04bhp   23.1 kmpl
1  Power Steering, Power Windows Front, Air Condi...    121.31bhp     17 kmpl
2  Power Steering, Power Windows Front, Air Condi...        84bhp  23.84 kmpl
3  Power Steering, Power Windows Front, Air Condi...     81.86bhp   19.1 kmpl
4  Power Steering, Power Windows Front, Air Condi...      88.5bhp  23.65 kmpl

                                            Car Link    Car Price
0  https://www.cardekho.com/used-car-details/used...     ₹ 4 Lakh
1  https://www.cardekho.com/buy-used-car-details/...  ₹ 8.11 Lakh
2  https://www.cardekho.com/used-car-details/used...  ₹ 5.85 Lakh
3  https://www.cardekho.com/buy-used-car-details/...  ₹ 4.62 Lakh
4  https://www.cardekho.com/used-car-details/used...  ₹ 7.90 Lakh
No numeric columns available for statistics.

Data Visualization for Bangalore:
No numeric columns available for visualization.

Feature Selection for Bangalore:
Target column 'Price' is not in the dataset.

3.Model Development

In [122]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Load datasets
datasets = {
    'Kolkata': pd.read_csv('kolkata_cars.csv'),
    'Chennai': pd.read_csv('chennai_cars.csv'),
    'Delhi': pd.read_csv('delhi_cars.csv'),
    'Hyderabad': pd.read_csv('hyderabad_cars.csv'),
    'Bangalore': pd.read_csv('bangalore_cars.csv')
}

# Define the target column
target_column = 'Price'

# Define models and hyperparameter grids
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(),
    'Random Forest': RandomForestRegressor(),
    'Gradient Boosting': GradientBoostingRegressor()
}

param_grids = {
    'Decision Tree': {
        'max_depth': [None, 10, 20, 30],
        'min_samples_split': [2, 5, 10]
    },
    'Random Forest': {
        'n_estimators': [50, 100, 200],
        'max_depth': [None, 10, 20, 30],
        'min_samples_split': [2, 5, 10]
    },
    'Gradient Boosting': {
        'n_estimators': [100, 200, 300],
        'learning_rate': [0.01, 0.1, 0.2],
        'max_depth': [3, 4, 5]
    }
}

# Function to evaluate model performance
def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    print(f"Model: {model.__class__.__name__}")
    print(f"Mean Squared Error: {mse:.2f}")
    print(f"R^2 Score: {r2:.2f}")
    print("-" * 30)

# Function to perform cross-validation
def cross_validate_model(model, X_train, y_train):
    scores = cross_val_score(model, X_train, y_train, cv=5, scoring='neg_mean_squared_error')
    print(f"Cross-validated Mean Squared Error: {-scores.mean():.2f}")

# Function to tune hyperparameters
def tune_hyperparameters(model, param_grid, X_train, y_train, search_method='grid'):
    if search_method == 'grid':
        search = GridSearchCV(model, param_grid, cv=5, n_jobs=-1, scoring='neg_mean_squared_error')
    elif search_method == 'random':
        search = RandomizedSearchCV(model, param_grid, n_iter=50, cv=5, n_jobs=-1, scoring='neg_mean_squared_error', random_state=42)
    else:
        raise ValueError("search_method must be 'grid' or 'random'")
    
    search.fit(X_train, y_train)
    print(f"Best Parameters for {model.__class__.__name__}: {search.best_params_}")
    print(f"Best Score: {-search.best_score_:.2f}")

# Apply functions to each city's dataset
for city_name, df in datasets.items():
    print(f"\nProcessing {city_name} Data:\n")
    
    # Verify if target column exists
    if target_column in df.columns:
        # Define features and target
        X = df.drop(columns=[target_column])
        y = df[target_column]
        
        # Split the dataset into training and testing sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        
        # Evaluate models
        print("Evaluating models...\n")
        for name, model in models.items():
            print(f"Evaluating {name} for {city_name}:")
            evaluate_model(model, X_train, X_test, y_train, y_test)
            cross_validate_model(model, X_train, y_train)
        
        # Tune hyperparameters
        print("\nTuning hyperparameters...\n")
        for name, model in models.items():
            if name in param_grids:
                print(f"Tuning {name} for {city_name}:")
                tune_hyperparameters(model, param_grids[name], X_train, y_train, search_method='grid')
            else:
                print(f"No hyperparameter tuning for {name}")
    else:
        print(f"Target column '{target_column}' not found in {city_name} dataset.")

Processing Kolkata Data:

Target column 'Price' not found in Kolkata dataset.

Processing Chennai Data:

Target column 'Price' not found in Chennai dataset.

Processing Delhi Data:

Target column 'Price' not found in Delhi dataset.

Processing Hyderabad Data:

Target column 'Price' not found in Hyderabad dataset.

Processing Bangalore Data:

Target column 'Price' not found in Bangalore dataset.

4.Code for Model Development and comparison

In [123]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load datasets
datasets = {
    'Kolkata': pd.read_csv('kolkata_cars.csv'),
    'Chennai': pd.read_csv('chennai_cars.csv'),
    'Delhi': pd.read_csv('delhi_cars.csv'),
    'Hyderabad': pd.read_csv('hyderabad_cars.csv'),
    'Bangalore': pd.read_csv('bangalore_cars.csv')
}

# Define the target column
target_column = 'Price'

# Define models
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(),
    'Random Forest': RandomForestRegressor(),
    'Gradient Boosting': GradientBoostingRegressor()
}

# Function to evaluate and compare models
def evaluate_and_compare_models(X_train, X_test, y_train, y_test):
    results = []
    
    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        
        mae = mean_absolute_error(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)
        
        results.append({
            'Model': name,
            'Mean Absolute Error': mae,
            'Mean Squared Error': mse,
            'R-squared': r2
        })
    
    results_df = pd.DataFrame(results)
    return results_df

# Apply functions to each city's dataset
for city_name, df in datasets.items():
    print(f"\nProcessing {city_name} Data:\n")
    
    # Verify if target column exists
    if target_column in df.columns:
        # Define features and target
        X = df.drop(columns=[target_column])
        y = df[target_column]
        
        # Split the dataset into training and testing sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        
        # Evaluate and compare models
        print("Evaluating and comparing models...\n")
        results_df = evaluate_and_compare_models(X_train, X_test, y_train, y_test)
        print(results_df)
    else:
        print(f"Target column '{target_column}' not found in {city_name} dataset.")

Processing Kolkata Data:

Target column 'Price' not found in Kolkata dataset.

Processing Chennai Data:

Target column 'Price' not found in Chennai dataset.

Processing Delhi Data:

Target column 'Price' not found in Delhi dataset.

Processing Hyderabad Data:

Target column 'Price' not found in Hyderabad dataset.

Processing Bangalore Data:

Target column 'Price' not found in Bangalore dataset.

5. Code for Optimization

In [124]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Lasso, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

# Load datasets
datasets = {
    'Kolkata': pd.read_csv('kolkata_cars.csv'),
    'Chennai': pd.read_csv('chennai_cars.csv'),
    'Delhi': pd.read_csv('delhi_cars.csv'),
    'Hyderabad': pd.read_csv('hyderabad_cars.csv'),
    'Bangalore': pd.read_csv('bangalore_cars.csv')
}

# Define the target column
target_column = 'Price'

# Function for feature engineering
def feature_engineering(df):
    # Example feature engineering
    if 'Year' in df.columns:
        df['Car_Age'] = 2024 - df['Year']
    if 'Mileage' in df.columns:
        df['Mileage_per_Year'] = df['Mileage'] / df['Car_Age']
    # Add more feature engineering based on domain knowledge and data exploration
    return df

# Function to evaluate and compare models
def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    return {
        'Mean Absolute Error': mae,
        'Mean Squared Error': mse,
        'R-squared': r2
    }

# Apply feature engineering and regularization models
for city_name, df in datasets.items():
    print(f"\nProcessing {city_name} Data:\n")
    
    # Verify if target column exists
    if target_column in df.columns:
        # Feature engineering
        df = feature_engineering(df)
        
        # Define features and target
        X = df.drop(columns=[target_column])
        y = df[target_column]
        
        # Split the dataset into training and testing sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        
        # Standardize features
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)
        
        # Regularization models
        lasso = Lasso()
        ridge = Ridge()
        
        # Hyperparameter tuning for Lasso and Ridge
        param_grid = {
            'alpha': [0.01, 0.1, 1, 10, 100]
        }
        
        lasso_grid = GridSearchCV(lasso, param_grid, cv=5, scoring='neg_mean_squared_error')
        ridge_grid = GridSearchCV(ridge, param_grid, cv=5, scoring='neg_mean_squared_error')
        
        lasso_grid.fit(X_train_scaled, y_train)
        ridge_grid.fit(X_train_scaled, y_train)
        
        print(f"Best Parameters for Lasso in {city_name}: {lasso_grid.best_params_}")
        print(f"Best Parameters for Ridge in {city_name}: {ridge_grid.best_params_}")
        
        # Evaluate models
        print("Evaluating Lasso model...\n")
        lasso_best = lasso_grid.best_estimator_
        lasso_results = evaluate_model(lasso_best, X_train_scaled, X_test_scaled, y_train, y_test)
        print(f"Lasso Results for {city_name}:")
        print(lasso_results)
        
        print("Evaluating Ridge model...\n")
        ridge_best = ridge_grid.best_estimator_
        ridge_results = evaluate_model(ridge_best, X_train_scaled, X_test_scaled, y_train, y_test)
        print(f"Ridge Results for {city_name}:")
        print(ridge_results)
        
    else:
        print(f"Target column '{target_column}' not found in {city_name} dataset.")

Processing Kolkata Data:

Target column 'Price' not found in Kolkata dataset.

Processing Chennai Data:

Target column 'Price' not found in Chennai dataset.

Processing Delhi Data:

Target column 'Price' not found in Delhi dataset.

Processing Hyderabad Data:

Target column 'Price' not found in Hyderabad dataset.

Processing Bangalore Data:

Target column 'Price' not found in Bangalore dataset.